### ISSUE TITLE
Julia 0.4

### ISSUE THREAD

**Issue by hombit** [JuliaLang/Sundials.jl#54]
Julia 0.4 is here: http://julialang.org/blog/2015/10/julia-0.4-release/
But tests are still failed for julia 0.4

**Comment by ViralBShah** [comment]
Packages will take a few days to catch up. There's also a boat load of deprecations here that need to be fixed here. PRs welcome.

**Comment by christianhaargaard** [comment]
Hey there. As I need Sundials and was a little too quick to upgrade to 0.4, I have decided I wanted to look at the code and see if I could do the changes that needs to be done. 

I have changed None to Union for a lot of the types parsed, changed intXX to IntXX and so forth, and I have succesfully made cvode_Roberts_dns.jl run. Hovewer, I have run into some trouble with cvode_Roberts_simplified.jl. 

When calling CVode in the solver loop I get an error saying 
~~~julia
ERROR: LoadError: StackOverflowError:
~~~.

If I run the code line by line, skipping the cvodefun-wrapper and using the function definition from cvode_Roberts_dns the CVode call in the loop runs fine.

**Comment by ViralBShah** [comment]
I get the segfault on OS X too, running `Pkg.test()`. Someone who knows this package well will have to dive in. I suspect that a bunch of the old `Ptr` stuff needs to be updated to `Ref`, and perhaps that could fix the segfault.

**Comment by ViralBShah** [comment]
Probably, we need to regenerate the ccall wrappers with Clang.jl for 0.4.

**Comment by ViralBShah** [comment]
Clang.jl seems to be updated for 0.4, so this may just require a regeneration.

**Comment by christianhaargaard** [comment]
Hmm. With the changes I mentioned above made I seem to primarily have a problem with the cvode_function that creates the c-callable function from my Julia function. If I run my code without that wrapper, and don't use the simple interface my own code runs (like the cvode_Roberts_dns example).

If you want to try it, it is here: 
https://github.com/christianhaargaard/Sundials.jl/tree/04upgrade

**Comment by ViralBShah** [comment]
We'll have to do it for all the functions, probably with clang.jl.

**Comment by christianhaargaard** [comment]
I think I didn't make myself clear - sorry. The c-wrappers are fine with the few search-and-replace changes I did (as far as I can tell). It might be worth it to redo them with Clang to guarantee consistency.

The wrapper I was mentioning above is the Julia-function that enables the simple interface. For the function to function properly it needs to make the supplied Julia (rhs) function c-callable. I guess I will try if I can make sense of the changes to cfunction and figure out what needs to be changed.

**Comment by acroy** [comment]
Sorry to join the party so late ...

@christianhaargaard : I had a look at your code and all you need is putting `Ref{Function}` instead of `Function` in the `cfunction` call (as @ViralBShah suspected). Note that the call to `CVodeFree` should read `CVodeFree([mem])` as discussed in #48. The same probably applies to IDA and KINSOL. Also note that `Ptr{:Union}` should probably be `Ptr{:Void}` (but maybe this amounts to the same effect). I think regenerating the bindings with Clang.jl would be the best solution - unfortunately I won't have time to dig into it. OTOH a quick solution that works would be nice since many people asked for it.

**Comment by christianhaargaard** [comment]
@acroy : Thanks, this was exactly the kind of feedback I was hoping for. Passing Ref{Function} instead of Function, and using CVodeFree([mem]) makes the example work. I have made the corresponding change to the other “simple” wrapper (kinsol and idasol) as well, and replaced Ptr{:Union} with Ptr{:Void}. The test passes now.

I have commited the source to the repository linked above - should I make a pull request for this? Just to have a temporary solution until someone redo the bindings with Clang.


—

**Comment by acroy** [comment]
@christianhaargaard : I would say we should have a PR with your changes to have a solution that works now - so it would IMO be great if you could do this. The only question is what we should do about the support of v0.3? Some of the changes could be handled via `Compat`, but I am not sure about `Ref`. I don't know how other packages are handling this? We could just have a branch for 0.3 support, where we apply bug-fixes for a while...

@ViralBShah : Do you have any ideas/suggestions?

**Comment by christianhaargaard** [comment]
@acroy I will see if I can figure out how to make a pull request :-) Also I noticed that the function for the simple interface to kinsol and idasol doesn't free the memory. So I added calls to `KINFree([kmem])` and `IDAFree([mem])` in `kinsol` and `idasol`.

**Comment by ViralBShah** [comment]
There can be a tagged version for 0.3, and going forward, we can choose to support only 0.4.

Cc @tkelman usually has better suggestions on these matters.

**Comment by tkelman** [comment]
Yes, change REQUIRE to 0.4 for anything that is 0.4 specific and be sure to `Pkg.tag("Sundials", :minor)` so 0.3 bugfixed could continue on a separate branch.

**Comment by acroy** [comment]
Done via #57.
